version: "3"
services:

  hao:
    restart: always
    image: ${HAO_IMAGE}
    container_name: hao_nginx
    volumes:
      - ./hao.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html:/usr/share/nginx/html
    ports:
      - "8080:80"